Repository antvis/Graphin, pull requests merged in 2019-12, with the labels that each got.

#32 docs: 🔍 Add algolia docsearchOptions
  packages/graphin-site/gatsby-config.js
  packages/graphin-site/package.json
Labels: PR: reviewed-changes-requested, documentation

#29 feat: using shallow equal for should update for deps
  packages/graphin/src/Graphin.tsx
  packages/graphin/src/__tests__/index.test.tsx
  packages/graphin/src/utils/index.ts
  packages/graphin/src/utils/shallowEqual.ts
Labels: PR: reviewed-changes-requested, enhancement

#37 Update gatsby-config.js
  packages/graphin-site/gatsby-config.js
Labels: PR: reviewed-changes-requested

#40 define getLayoutInfo's return type
  .eslintrc.js
  package.json
  packages/graphin-site/docs/api/extend.en.md
  packages/graphin-site/docs/api/extend.zh.md
  packages/graphin/src/Graphin.tsx
  packages/graphin/src/controller/layout/index.tsx
  packages/graphin/src/types.ts
Labels: PR: unreviewed

#18 Feature/demos
  packages/graphin-site/examples/case/kownledge-graph/demo/Movie.tsx
  packages/graphin-site/examples/case/kownledge-graph/demo/meta.json
  packages/graphin-site/examples/case/kownledge-graph/index.zh.md
  packages/graphin-site/examples/case/network-analysis/demo/XiaoMi.tsx
  packages/graphin-site/examples/case/network-analysis/demo/meta.json
  packages/graphin-site/examples/case/network-analysis/index.zh.md
  packages/graphin-site/examples/data/honglou.json
  packages/graphin-site/examples/layout/force/demo/Force.jsx
  packages/graphin-site/examples/layout/force/demo/ForceWithCentripetal.jsx
  packages/graphin-site/examples/layout/force/demo/meta.json
  packages/graphin-site/examples/layout/force/index.zh.md
  packages/graphin-site/examples/layout/grid/demo/Grid.jsx
  packages/graphin-site/examples/layout/grid/demo/meta.json
  packages/graphin-site/examples/layout/grid/index.zh.md
  packages/graphin-site/examples/render/expand/demo/AddNode.jsx
  packages/graphin-site/examples/render/expand/demo/NodeExpand.jsx
  packages/graphin-site/examples/render/expand/demo/meta.json
  packages/graphin-site/examples/render/expand/index.zh.md
  packages/graphin-site/examples/render/save/demo/meta.json
  packages/graphin-site/examples/render/save/demo/renderSavedGraph.jsx
  packages/graphin-site/examples/render/save/index.zh.md
  packages/graphin-site/examples/render/simple/demo/meta.json
  packages/graphin-site/examples/render/simple/demo/renderRandomData.jsx
  packages/graphin-site/examples/render/simple/index.zh.md
  packages/graphin-site/examples/shape/node/demo/CustomNode.jsx
  packages/graphin-site/examples/shape/node/demo/DefaultNode.jsx
  packages/graphin-site/examples/shape/node/demo/meta.json
  packages/graphin-site/examples/shape/node/index.zh.md
  packages/graphin-site/gatsby-browser.js
  packages/graphin-site/gatsby-config.js
  packages/graphin-site/package.json
  packages/graphin-site/site/pages/index.zh.tsx
  packages/graphin/package.json
  packages/graphin/src/shape/render/CircleNode.ts
  packages/graphin/src/types.ts
Labels: PR: unreviewed

#43 feat: export the layout methods. add: subgraph layout demo on site.
  .eslintrc.js
  packages/graphin-site/examples/layout/sublayout/demo/Sublayout.jsx
  packages/graphin-site/examples/layout/sublayout/demo/meta.json
  packages/graphin-site/examples/layout/sublayout/index.zh.md
  packages/graphin-site/package.json
  packages/graphin/src/controller/layout/index.tsx
  packages/graphin/src/index.ts
  packages/graphin/src/layout/index.ts
Labels: PR: unreviewed, enhancement
