Repository antvis/Graphin, pull requests merged in 2020-04, with the labels that each got.

#76 :memo: docs(common): fix behavior document
  packages/graphin-site/docs/manual/advanced-guides/register.en.md
  packages/graphin-site/docs/manual/advanced-guides/register.zh.md
Labels: PR: unreviewed, memo

#77 Hotfix/extend layout option
  packages/graphin/src/controller/layout/defaultLayouts.ts
Labels: PR: unreviewed

#78 Feature/merge graph studio shape
  lerna.json
  packages/graphin/src/controller/layout/dataChecking.ts
  packages/graphin/src/controller/register.ts
  packages/graphin/src/shape/graph-studio/CircleNode.ts
  packages/graphin/src/shape/graph-studio/HexagonNode.ts
  packages/graphin/src/shape/graph-studio/LineEdge.ts
  packages/graphin/src/shape/graph-studio/LoopEdge.ts
  packages/graphin/src/shape/graph-studio/PointNode.ts
  packages/graphin/src/shape/graph-studio/RectNode.ts
  packages/graphin/src/shape/graph-studio/StubNode.ts
  packages/graphin/src/shape/graph-studio/constants.ts
  packages/graphin/src/shape/graph-studio/utils.ts
  packages/graphin/src/types.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: unreviewed

#85 fix: replace tnpm with yarn to avoid ci error
  lerna.json
Labels: PR: unreviewed, bug

#83 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved, chore

#86 fix: support user defined property in date props
  packages/graphin/src/types.ts
Labels: PR: reviewed-changes-requested, bug

#82 show line dash and line width demo
  packages/graphin-site/examples/case/anti-fraud/demo/Simple.jsx
  packages/graphin-site/examples/case/graph-knowledge/demo/Simple.jsx
  packages/graphin-site/examples/case/graph-knowledge/demo/meta.json
  packages/graphin-site/examples/case/graph-knowledge/index.zh.md
Labels: PR: unreviewed

#88 :hankey: chore(common): add change log generator tool
  CHANGELOG.md
  package.json
  packages/graphin-site/examples/shape/node/demo/CanonicalShape.jsx
Labels: PR: unreviewed, hankey

#89 Feature/update change log
  CHANGELOG.md
  package.json
  packages/graphin-site/examples/shape/node/demo/CanonicalShape.jsx
Labels: PR: unreviewed

#90 Feature/prettier code
  packages/graphin-components/src/components/toolbar/useFullscreen.ts
  packages/graphin-components/src/components/toolbar/useZoom.ts
  packages/graphin-studio/.prettierrc.js
  packages/graphin-studio/src/Components/Layout/types.ts
  packages/graphin-studio/src/Components/SearchBar/interface.ts
  packages/graphin-studio/src/Components/TreeSelector/functions/getCheckedKeys.ts
  packages/graphin-studio/src/Components/TreeSelector/interface.ts
  packages/graphin-studio/src/Components/index.ts
  packages/graphin-studio/src/Core/AddNodes/interface.ts
  packages/graphin-studio/src/Core/DiffusePanel/interface.ts
  packages/graphin-studio/src/Core/GraphDrawer/interface.ts
  packages/graphin-studio/src/Core/Setting/interface.ts
  packages/graphin-studio/src/Core/Styling/interface.ts
  packages/graphin-studio/src/Custom/config.ts
  packages/graphin-studio/src/Custom/renderContextMenu.ts
  packages/graphin-studio/src/Custom/transform.ts
  packages/graphin-studio/src/Events/canvas-click.ts
  packages/graphin-studio/src/Events/node-click.ts
  packages/graphin-studio/src/Events/useGraphEvents.ts
  packages/graphin-studio/src/Extend/RectNodeShape.ts
  packages/graphin-studio/src/Extend/index.ts
  packages/graphin-studio/src/Extend/layout.ts
  packages/graphin-studio/src/Extend/marker.ts
  packages/graphin-studio/src/Redux/reducer.ts
  packages/graphin-studio/src/Redux/reducer/changeToolbar.ts
  packages/graphin-studio/src/Redux/reducer/deleteNodes.ts
  packages/graphin-studio/src/Redux/reducer/diffuse.ts
  packages/graphin-studio/src/Redux/store.ts
  packages/graphin-studio/src/Service/Mock/edgeTypes.ts
  packages/graphin-studio/src/Service/Mock/nodePropertiesSchema.ts
  packages/graphin-studio/src/Service/Mock/nodeTypes.ts
  packages/graphin-studio/src/Service/Storage/LocalStorage.ts
  packages/graphin-studio/src/Service/getNodeProperties.ts
  packages/graphin-studio/src/Service/getNodesById.ts
  packages/graphin-studio/src/Service/index.ts
  packages/graphin-studio/src/Utils/helper.ts
  packages/graphin-studio/src/Utils/hexoToRgba.ts
  packages/graphin-studio/src/index.d.ts
  packages/graphin-studio/src/types.ts
  packages/graphin/src/__tests__/helper.ts
  packages/graphin/src/apis/highlight.ts
  packages/graphin/src/apis/search.ts
  packages/graphin/src/behaviors/graphin-highlight.ts
  packages/graphin/src/controller/__tests__/dataChecking.test.ts
  packages/graphin/src/controller/layout/dataChecking.ts
  packages/graphin/src/controller/register.ts
  packages/graphin/src/icons/iconFont.ts
  packages/graphin/src/icons/marker.ts
  packages/graphin/src/layout/basic/concentric.ts
  packages/graphin/src/layout/basic/forceWithWorker.ts
  packages/graphin/src/layout/basic/random.ts
  packages/graphin/src/layout/basic/worker.ts
  packages/graphin/src/layout/force/ForceLayout.ts
  packages/graphin/src/layout/utils/graph.ts
  packages/graphin/src/perf/optimizeDrawing.ts
  packages/graphin/src/shape/render/compiler.ts
  packages/graphin/src/utils/__tests__/mock.test.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: reviewed-changes-requested

#93 Doc/graphin shape demo
  packages/graphin-components/jest.config.js
  packages/graphin-components/package.json
  packages/graphin-components/src/components/ui/index.ts
  packages/graphin-components/tsconfig.json
  packages/graphin-site/examples/case/anti-fraud/demo/Simple.jsx
  packages/graphin-site/examples/case/graph-knowledge/demo/Simple.jsx
  packages/graphin-site/examples/case/identification/demo/Simple.jsx
  packages/graphin-site/examples/layout/base/demo/Dagre.jsx
  packages/graphin-site/examples/layout/base/demo/Radial.jsx
  packages/graphin-site/examples/render/simple/demo/renderRandomData.jsx
  packages/graphin-site/examples/shape/node/demo/DefaultNode.jsx
  packages/graphin-site/examples/shape/node/demo/InnerShape.jsx
  packages/graphin-site/examples/shape/node/demo/meta.json
  packages/graphin-site/examples/shape/node/index.zh.md
  packages/graphin-site/package.json
  packages/graphin/src/__tests__/index.test.tsx
  packages/graphin/src/controller/layout/dataChecking.ts
  packages/graphin/src/controller/register.ts
  packages/graphin/src/shape/g6/LineEdge.ts
  packages/graphin/src/shape/graph-studio/CircleNode.ts
  packages/graphin/src/shape/graph-studio/HexagonNode.ts
  packages/graphin/src/shape/graph-studio/LineEdge.ts
  packages/graphin/src/shape/graph-studio/LoopEdge.ts
  packages/graphin/src/shape/graph-studio/PointNode.ts
  packages/graphin/src/shape/graph-studio/RectNode.ts
  packages/graphin/src/shape/graph-studio/StubNode.ts
  packages/graphin/src/shape/render/SimplicityNode.ts
  packages/graphin/src/types.ts
  packages/graphin/src/utils/__tests__/__snapshots__/mock.test.ts.snap
  packages/graphin/src/utils/mock.ts
  packages/graphin/tsconfig.json
Labels: PR: unreviewed

#87 :sparkles: add advanced example:find-connections and node-expand
  packages/graphin-site/examples/advanced/find-connections/demo/Simple.jsx
  packages/graphin-site/examples/advanced/find-connections/demo/meta.json
  packages/graphin-site/examples/advanced/find-connections/index.zh.md
  packages/graphin-site/examples/advanced/layout-switching/demo/Simple.jsx
  packages/graphin-site/examples/advanced/layout-switching/demo/meta.json
  packages/graphin-site/examples/advanced/layout-switching/index.zh.md
  packages/graphin-site/examples/advanced/node-expand/demo/Dagre.jsx
  packages/graphin-site/examples/advanced/node-expand/demo/Force.jsx
  packages/graphin-site/examples/advanced/node-expand/demo/meta.json
  packages/graphin-site/examples/advanced/node-expand/index.zh.md
  packages/graphin-site/examples/case/identification/demo/Simple.jsx
  packages/graphin-site/examples/components/toolbar/demo/Simple.jsx
  packages/graphin-site/gatsby-config.js
Labels: PR: reviewed-approved, sparkles

#98 Upgrade antd version to 4.0
  packages/graphin-components/package.json
  packages/graphin-components/src/components/context-menu/Container.tsx
  packages/graphin-components/src/components/context-menu/__tests__/index.test.tsx
  packages/graphin-components/src/components/toolbar/index.tsx
  packages/graphin-components/src/components/ui/index.ts
  packages/graphin-site/docs/api/components.zh.md
  packages/graphin-site/examples/components/contextmenu/demo/Simple.jsx
  packages/graphin-site/examples/components/toolbar/demo/Custom.jsx
  packages/graphin-site/gatsby-browser.js
  packages/graphin-site/package.json
  packages/graphin-studio/package.json
  packages/graphin-studio/public/index.html
  packages/graphin-studio/src/Components/SearchBar/Panel.tsx
  packages/graphin-studio/src/Components/SearchBar/SearchBar.tsx
  packages/graphin-studio/src/Components/ToolBar/ToolBar.tsx
  packages/graphin-studio/src/Components/TreeSelector/TreeSelector.tsx
  packages/graphin-studio/src/Core/Clear/index.tsx
  packages/graphin-studio/src/Core/LayoutSelector/Radio.tsx
  packages/graphin-studio/src/Core/LayoutSelector/Selector.tsx
  packages/graphin-studio/src/Core/OperatorBar/index.tsx
  packages/graphin-studio/src/Custom/renderContextMenu.tsx
  packages/graphin-studio/src/Custom/renderToolbar.tsx
  packages/graphin-studio/src/Graph.tsx
  packages/graphin-studio/src/GraphinStudio.tsx
  packages/graphin-studio/src/index.tsx
  packages/graphin-studio/src/types.ts
  packages/graphin-studio/webpack.config.js
  packages/graphin/src/index.less
  packages/graphin/src/index.ts
Labels: PR: unreviewed
