Repository antvis/Graphin, pull requests merged in 2020-06, with the labels that each got.

#138 support poly edge
  package.json
  packages/graphin-site/examples/shape/edge/demo/PolyEdgeShape.jsx
  packages/graphin-site/examples/shape/edge/demo/meta.json
  packages/graphin-site/examples/shape/edge/index.zh.md
  packages/graphin-site/examples/shape/node/demo/InnerShape.jsx
  packages/graphin-site/examples/shape/node/index.zh.md
  packages/graphin/package.json
  packages/graphin/src/Graphin.tsx
  packages/graphin/src/controller/__tests__/dataChecker.test.ts
  packages/graphin/src/controller/init.ts
  packages/graphin/src/controller/layout/dataChecker.ts
  packages/graphin/src/controller/layout/dataChecking.ts
  packages/graphin/src/controller/layout/index.tsx
  packages/graphin/src/controller/register.ts
  packages/graphin/src/shape/graph-studio/PolyEdge.ts
  packages/graphin/src/types.ts
Labels: PR: reviewed-changes-requested

#136 upgrade @antv/g6 to 3.5
  README.md
  packages/graphin-components/package.json
  packages/graphin-components/src/components/context-menu/__tests__/index.test.tsx
  packages/graphin-components/src/components/context-menu/types.ts
  packages/graphin-components/src/components/context-menu/useContextmenu.ts
  packages/graphin-components/src/components/toolbar/__tests__/index.test.tsx
  packages/graphin-site/examples/advanced/find-connections/demo/Simple.jsx
  packages/graphin-site/examples/advanced/node-expand/demo/Dagre.jsx
  packages/graphin-site/examples/advanced/node-expand/demo/Force.jsx
  packages/graphin-site/examples/layout/force/demo/Big.jsx
  packages/graphin-site/package.json
  packages/graphin-studio/package.json
  packages/graphin-studio/src/Core/AddNodes/Normal.tsx
  packages/graphin-studio/src/Core/Styling/NodeColorPicker.tsx
  packages/graphin-studio/src/types.ts
  packages/graphin/package.json
  packages/graphin/src/Graphin.tsx
  packages/graphin/src/__tests__/index.test.tsx
  packages/graphin/src/apis/__tests__/search.test.ts
  packages/graphin/src/apis/getInfo.ts
  packages/graphin/src/apis/highlight.ts
  packages/graphin/src/apis/search.ts
  packages/graphin/src/behaviors/graphin-highlight.ts
  packages/graphin/src/controller/init.ts
  packages/graphin/src/controller/layout/defaultLayouts.ts
  packages/graphin/src/controller/register.ts
  packages/graphin/src/events/change-zoom.ts
  packages/graphin/src/events/window-resize.ts
  packages/graphin/src/icons/marker.ts
  packages/graphin/src/index.ts
  packages/graphin/src/layout/basic/concentric.ts
  packages/graphin/src/layout/basic/force.ts
  packages/graphin/src/layout/basic/grid.ts
  packages/graphin/src/layout/basic/tweak.ts
  packages/graphin/src/layout/force/Elements.ts
  packages/graphin/src/layout/force/ForceLayout.ts
  packages/graphin/src/layout/g6/__tests__/__snapshots__/dagre.test.ts.snap
  packages/graphin/src/layout/g6/__tests__/__snapshots__/radial.test.ts.snap
  packages/graphin/src/layout/g6/__tests__/dagre.test.ts
  packages/graphin/src/layout/g6/dagre.ts
  packages/graphin/src/perf/optimizeDrawing.ts
  packages/graphin/src/shape/g6/LineEdge.ts
  packages/graphin/src/shape/g6/setState.edge.ts
  packages/graphin/src/shape/graph-studio/CircleNode.ts
  packages/graphin/src/shape/graph-studio/HexagonNode.ts
  packages/graphin/src/shape/graph-studio/LineEdge.ts
  packages/graphin/src/shape/graph-studio/LoopEdge.ts
  packages/graphin/src/shape/graph-studio/PointNode.ts
  packages/graphin/src/shape/graph-studio/RectNode.ts
  packages/graphin/src/shape/graph-studio/StubNode.ts
  packages/graphin/src/shape/render/SimplicityNode.ts
  packages/graphin/src/shape/render/compiler.ts
  packages/graphin/src/types.ts
  packages/graphin/src/utils/__tests__/deepEqual.test.ts
  packages/graphin/src/utils/deepEqual.ts
Labels: PR: unreviewed

#137 feat(graphin): add node combo feature
  packages/graphin-site/examples/advanced/node-combo/demo/Force.jsx
  packages/graphin-site/examples/advanced/node-combo/demo/Simple.jsx
  packages/graphin-site/examples/advanced/node-combo/demo/meta.json
  packages/graphin-site/examples/advanced/node-combo/index.en.md
  packages/graphin-site/examples/advanced/node-combo/index.zh.md
  packages/graphin/src/controller/init.ts
  packages/graphin/src/controller/layout/index.tsx
  packages/graphin/src/shape/graph-studio/PolyEdge.ts
  packages/graphin/src/types.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: unreviewed, enhancement

#117 feat(components): Add Legend Component
  package.json
  packages/graphin-components/src/components/legend/__tests__/index.test.tsx
  packages/graphin-components/src/components/legend/index.less
  packages/graphin-components/src/components/legend/index.tsx
  packages/graphin-components/src/index.ts
  packages/graphin-site/docs/api/components.en.md
  packages/graphin-site/docs/api/components.zh.md
  packages/graphin-site/examples/advanced/layout-switching/demo/Simple.jsx
  packages/graphin-site/examples/components/legend/demo/Filter.jsx
  packages/graphin-site/examples/components/legend/demo/Highlight.jsx
  packages/graphin-site/examples/components/legend/demo/meta.json
  packages/graphin-site/examples/components/legend/index.en.md
  packages/graphin-site/examples/components/legend/index.zh.md
  packages/graphin/src/events/change-zoom.ts
Labels: PR: reviewed-changes-requested, enhancement

#139 fix: readme npm command error
  README.md
Labels: PR: unreviewed, bug

#141 fix ci for v1.4.0-graphin
  packages/graphin-components/src/components/legend/__tests__/index.test.tsx
  packages/graphin-components/src/components/legend/index.tsx
  packages/graphin/src/Graphin.tsx
  packages/graphin/src/controller/layout/defaultLayouts.ts
  packages/graphin/src/controller/layout/index.tsx
  packages/graphin/src/layout/basic/forceWithWorker.ts
  packages/graphin/src/layout/basic/random.ts
  packages/graphin/src/layout/force/ForceLayout.ts
  packages/graphin/src/layout/g6/__tests__/__snapshots__/radial.test.ts.snap
  packages/graphin/src/layout/g6/__tests__/dagre.test.ts
  packages/graphin/src/shape/render/compiler.ts
  packages/graphin/src/types.ts
  packages/graphin/src/utils/__tests__/__snapshots__/mock.test.ts.snap
  packages/graphin/src/utils/__tests__/deepEqual.test.ts
  packages/graphin/src/utils/deepEqual.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: reviewed-changes-requested

#143 fix poly edge display error
  packages/graphin-site/examples/shape/edge/demo/PolyEdgeShape.jsx
  packages/graphin/src/controller/layout/dataChecker.ts
  packages/graphin/src/shape/graph-studio/PolyEdge.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: reviewed-changes-requested

#144 Example/node combo static layout
  packages/graphin-site/examples/advanced/node-combo/demo/Force.jsx
  packages/graphin-site/examples/advanced/node-combo/demo/Simple.jsx
  packages/graphin-site/examples/advanced/node-combo/demo/meta.json
Labels: PR: unreviewed

#146 :bookmark: release(common): v1.4.1
  CHANGELOG.md
  packages/graphin/package.json
Labels: PR: unreviewed, bookmark

#147 Fix right click bug of context menu.
  packages/graphin-components/src/components/context-menu/useContextmenu.ts
Labels: PR: reviewed-changes-requested

#151 fix: #150 (resolved)-legend not updating on props update
  packages/graphin-components/src/components/legend/__tests__/index.test.tsx
  packages/graphin-components/src/components/legend/index.tsx
Labels: PR: unreviewed, bug
