Repository antvis/Graphin, pull requests merged in 2020-08, with the labels that each got.

#163 Fix the bug of preset force layout
  packages/graphin/package.json
  packages/graphin/src/controller/layout/defaultLayouts.ts
Labels: PR: reviewed-changes-requested

#168 BugFix:fix graphin highlight.dark behavior
  packages/graphin-components/src/components/toolbar/index.tsx
  packages/graphin/src/behaviors/graphin-highlight.ts
Labels: PR: reviewed-changes-requested

#169 :bug: fix(common): force set function name for uglify js will skip it
  packages/graphin/src/layout/basic/forceWithWorker.ts
Labels: PR: reviewed-changes-requested, bug

#172 :bug: fix(common): fix position not updated when draging node
  packages/graphin/src/controller/init.ts
  packages/graphin/src/events/drag-with-force.ts
Labels: PR: unreviewed, bug
