Repository antvis/Graphin, pull requests merged in 2020-03, with the labels that each got.

#63 fix: Support multiple behavior modes closes #62
  packages/graphin/src/controller/init.ts
Labels: PR: reviewed-changes-requested, bug

#65 :sparkles: feat(common): replace graphin studio with graph studio
  lerna.json
  packages/graphin-site/site/locale.json
  packages/graphin-site/site/pages/index.less
  packages/graphin-site/site/pages/index.zh.tsx
Labels: PR: unreviewed, sparkles

#70 Feature/opt foce layout worker
  package.json
  packages/graphin-site/examples/layout/force/demo/Big.jsx
  packages/graphin/src/controller/layout/defaultLayouts.ts
  packages/graphin/src/layout/basic/force.ts
  packages/graphin/src/layout/basic/forceWithWorker.ts
  packages/graphin/src/layout/basic/worker.ts
  packages/graphin/src/layout/force/ForceLayout.ts
Labels: PR: unreviewed

#68 Feature/force layout worker
  package.json
  packages/graphin-site/docs/api/layout.en.md
  packages/graphin-site/docs/api/layout.zh.md
  packages/graphin-site/examples/data/web.json
  packages/graphin-site/examples/layout/force/demo/Big.jsx
  packages/graphin-site/examples/layout/force/demo/Force.jsx
  packages/graphin-site/examples/layout/force/demo/ForceWithCentripetal.jsx
  packages/graphin-site/examples/layout/force/demo/meta.json
  packages/graphin/src/controller/layout/defaultLayouts.ts
  packages/graphin/src/layout/basic/force.ts
  packages/graphin/src/layout/basic/forceWithWorker.ts
  packages/graphin/src/layout/basic/worker.ts
  packages/graphin/src/layout/force/ForceLayout.ts
  packages/graphin/src/layout/force/Point.ts
  packages/graphin/src/layout/force/Vector.ts
Labels: PR: reviewed-approved

#69 :package: dep_up(common): upgrade prettier to 2.0.2 to support ts optional chain
  packages/graphin-components/src/components/toolbar/useFullscreen.ts
  packages/graphin-components/src/components/toolbar/useZoom.ts
  packages/graphin-studio/src/Components/TreeSelector/functions/getCheckedKeys.ts
  packages/graphin-studio/src/Custom/renderContextMenu.ts
  packages/graphin-studio/src/Custom/transform.ts
  packages/graphin-studio/src/Events/useGraphEvents.ts
  packages/graphin-studio/src/Extend/RectNodeShape.ts
  packages/graphin-studio/src/Extend/layout.ts
  packages/graphin-studio/src/Redux/reducer.ts
  packages/graphin-studio/src/Redux/reducer/changeToolbar.ts
  packages/graphin-studio/src/Redux/reducer/deleteNodes.ts
  packages/graphin-studio/src/Redux/reducer/diffuse.ts
  packages/graphin-studio/src/Service/getNodeProperties.ts
  packages/graphin-studio/src/Service/getNodesById.ts
  packages/graphin-studio/src/Service/index.ts
  packages/graphin-studio/src/Utils/helper.ts
  packages/graphin/src/__tests__/helper.ts
  packages/graphin/src/apis/highlight.ts
  packages/graphin/src/apis/search.ts
  packages/graphin/src/behaviors/graphin-highlight.ts
  packages/graphin/src/controller/__tests__/dataChecking.test.ts
  packages/graphin/src/controller/layout/dataChecking.ts
  packages/graphin/src/controller/register.ts
  packages/graphin/src/icons/iconFont.ts
  packages/graphin/src/icons/marker.ts
  packages/graphin/src/layout/basic/concentric.ts
  packages/graphin/src/layout/basic/random.ts
  packages/graphin/src/layout/utils/graph.ts
  packages/graphin/src/perf/optimizeDrawing.ts
  packages/graphin/src/shape/render/compiler.ts
  packages/graphin/src/utils/__tests__/mock.test.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: unreviewed, package

#67 Fix/toolbar full screen bug
  packages/graphin-components/src/components/context-menu/Container.tsx
  packages/graphin-components/src/components/context-menu/getPosition.ts
  packages/graphin-components/src/components/toolbar/__tests__/index.test.tsx
  packages/graphin-components/src/components/toolbar/index.less
  packages/graphin-components/src/components/toolbar/index.tsx
  packages/graphin-components/src/components/ui/index.ts
  packages/graphin-site/examples/components/toolbar/demo/Simple.jsx
  packages/graphin/src/Graphin.tsx
Labels: PR: reviewed-changes-requested

#72 feature: add tree for mock
  packages/graphin/src/utils/Tree.ts
  packages/graphin/src/utils/mock.ts
Labels: PR: unreviewed, feature
