Repository antvis/Graphin, pull requests merged in 2021-03, with the labels that each got.

#225 chore: update version to solve @antv/layout problem
  packages/graphin/package.json
Labels: PR: unreviewed

#226 chore: release version 2.0.3
  packages/graphin/docs/render/update/index.md
  packages/graphin/docs/render/update/node.tsx
  packages/graphin/docs/render/update/state.tsx
  packages/graphin/package.json
  packages/graphin/src/shape/graphin-circle.ts
  packages/graphin/src/shape/utils.ts
  packages/graphin/src/utils/index.ts
Labels: PR: unreviewed

#229 chore: release graphin 2.0.4
  CHANGELOG.md
  packages/graphin-components/package.json
  packages/graphin/docs/behaviors/demos/drag-force-node.tsx
  packages/graphin/docs/behaviors/node.en-US.md
  packages/graphin/docs/behaviors/node.md
  packages/graphin/docs/solution/graph-database/graph-schema/index.md
  packages/graphin/docs/solution/graph-database/graph-schema/index.tsx
  packages/graphin/package.json
  packages/graphin/src/Graphin.tsx
  packages/graphin/src/GraphinContext.tsx
  packages/graphin/src/behaviors/DragNodeWithForce.tsx
  packages/graphin/src/behaviors/index.tsx
Labels: PR: unreviewed

#231 fix: defaultNode/defaultEdge/defaultCombo with error type, closes: #230
  packages/graphin/src/typings/type.ts
Labels: PR: reviewed-approved

#233 chore: release graphin 2.0.5
  packages/graphin-components/package.json
  packages/graphin-components/src/Tooltip/Node.tsx
  packages/graphin-components/src/Tooltip/demos/Antd.tsx
  packages/graphin-components/src/Tooltip/demos/AntdWithContextMenu.tsx
  packages/graphin-components/src/Tooltip/demos/Custom.tsx
  packages/graphin-components/src/Tooltip/demos/index.tsx
  packages/graphin-components/src/Tooltip/index.en-US.md
  packages/graphin-components/src/Tooltip/index.less
  packages/graphin-components/src/Tooltip/index.md
  packages/graphin-components/src/Tooltip/index.tsx
  packages/graphin/docs/render/element/demos/node.tsx
  packages/graphin/package.json
  packages/graphin/src/typings/type.ts
Labels: PR: reviewed-changes-requested
